"""empty message

Revision ID: 379946dd5b44
Revises: 
Create Date: 2019-10-14 00:55:53.642492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379946dd5b44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'image',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'image',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
