"""empty message

Revision ID: 5f94df0184af
Revises: 051814516ff5
Create Date: 2019-11-24 04:12:47.946943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f94df0184af'
down_revision = '051814516ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('credit_card', sa.Integer(), nullable=True))
    op.add_column('credit_cards', sa.Column('exp_month', sa.Integer(), nullable=True))
    op.add_column('credit_cards', sa.Column('exp_year', sa.Integer(), nullable=True))
    op.add_column('credit_cards', sa.Column('security_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'security_code')
    op.drop_column('credit_cards', 'exp_year')
    op.drop_column('credit_cards', 'exp_month')
    op.drop_column('credit_cards', 'credit_card')
    # ### end Alembic commands ###
