"""empty message

Revision ID: 915661ab4a46
Revises: 
Create Date: 2019-11-24 00:51:33.659272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915661ab4a46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
