"""added features table

Revision ID: bd204229b6d4
Revises: a338c65d2302
Create Date: 2019-10-20 04:48:57.175786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd204229b6d4'
down_revision = 'a338c65d2302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.Text(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_features')
    # ### end Alembic commands ###
