"""empty message

Revision ID: ca87df6a839e
Revises: 5f94df0184af
Create Date: 2019-12-02 03:17:55.307667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca87df6a839e'
down_revision = '5f94df0184af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('credit_cards', sa.Column('address_2', sa.String(length=300), nullable=True))
    op.add_column('credit_cards', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('credit_cards', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('credit_cards', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('credit_cards', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'state')
    op.drop_column('credit_cards', 'postal_code')
    op.drop_column('credit_cards', 'country')
    op.drop_column('credit_cards', 'city')
    op.drop_column('credit_cards', 'address_2')
    op.drop_column('credit_cards', 'address')
    # ### end Alembic commands ###
